# Generated by Django 2.1 on 2018-08-21 22:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180821_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
