# Generated by Django 2.1 on 2018-08-19 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180818_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 2, 49, 5, 856, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
